version: "3.8"

services:
  reactapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontned
    ports:
      - "3000:5173"
    networks:
      - admin
    
networks:
    admin:
        external: true