version: "3.8"

services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodeapp
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    ports:
      - "4010:4000"
    networks:
      - admin

networks:
    admin:
        external: true